---
title: "A Tale To Tell"
subtitle: "But Not Yet ..."
author:  'Mickaël Canouil, _Ph.D._'
date: '`r format(Sys.Date(), "%B %d, %Y")`'
knit: (function(inputFile, encoding) rmarkdown::render(inputFile, encoding = encoding, output_file = "docs/index.html"))
params:
  content: ['Rmd/content.Rmd']
output:
  xaringan::moon_reader:
    self_contained: true
    css: ["default", "utils/default.css", "utils/fonts.css"]
    includes:
      in_header: utils/_favicon.html
      after_body: utils/_scripts.html
    nature:
      highlightStyle: github
      highlightLines: true
      slideNumberFormat: "%current%"
      ratio: "16:9"
      countIncrementalSlides: false
---

```{r setup, include = FALSE}
options("width" = 110)
options(htmltools.dir.version = FALSE)

suppressPackageStartupMessages({
  library(here)
  library(knitr)
  library(ragg)
  library(svglite)
  library(ggplot2)
  library(ggtext)
  library(patchwork)
  library(data.table)
  library(showtext)
})
```

```{r setup-knitr, include = FALSE}
opts_chunk$set(
  eval = TRUE, # Default: TRUE
  include = TRUE, # Default: TRUE
  echo = TRUE, # Default: TRUE
  width = getOption("width"),
  comment = "#>", 
  fig.align = "center",
  fig.width = 11.5, # Default: 7
  fig.height = 5.75,  # Default: 7
  dpi = 150, # Default: 72
  dev = "ragg_png", # Alt: ragg_png
  dev.args = list(
    web_fonts = list("https://fonts.googleapis.com/css?family=Caveat")
  )
)
font_add_google("Caveat", "Caveat", regular.wt = 400)
showtext_auto()
```

```{r, child = params[["content"]]}
```
